[package]
name = "FlyingCircus"
version = "3.0.0"
compiler = "0.11.0"
entrypoint = "src/FlyingCircus.typ"
repository = "https://github.com/typst/templates"
authors = ["Tetragramm <https://typst.app>"]
license = "MIT"
description = "For creating homebrew documents with the same fancy style as the Flying Circus book? Provides simple commands to generate a whole aircraft stat page, vehicle, or even ship."
keywords = ["Flying Circus", "RPG", "TTRPG"]
categories = ["book", "fun", "layout"]
disciplines = ["engineering","design","transportation"]

[template]
path = "template"
entrypoint = "Main.typ"
thumbnail = "thumbnail.png"